### ISSUE TITLE
Double click on a regexp result brings to the relevant line

### ISSUE THREAD

**Issue by IvanoAlvino** [joffrey-bion/fx-log#46] opened 2016-02-23 16:57 UTC
It would be nice (if doable) when searching using a regexp, to double click on a result line and to be brought directly to the relevant line in the full log.
Useful when you filter something using a regexp and than want to read what happened before and after a certain result.

**Comment by joffrey-bion** [comment] 2016-02-23 19:12
This is a duplicate of issue https://github.com/joffrey-bion/fx-log/issues/34
(with the addition of the double-click shortcut)

**Closed as completed by joffrey-bion** 2016-02-23 19:12 UTC
Labels: duplicate
